CommonArguments:
  data_split_type: ["train", "test"]
  data_split_ratio: 0.2
  

SentimentArguments:
  feature_column_name: "text"
  label_column_name: "sentiment"
  sentiment_class_dict: {
        "negative": 0,
        "neutral": 1,
        "positive": 2,
  }  
  num_train_epochs: 3
  dropout_parameter: 0.3  
  batch_size: 256
  max_length: 160  