artifacts_root: artifacts

#<-------------- Sentiment ----------------------->
sentiment_data_ingestion:
  root_dir: artifacts/sentiment/data_ingestion/
  unzip_dir: artifacts/sentiment/data_ingestion/
  local_data_file: artifacts/sentiment/data_ingestion/data.zip
  # use-case specific parameters
  source_URL: "abhi8923shriv/sentiment-analysis-dataset"  
  outsource_file: sentiment-analysis-dataset.zip
  

sentiment_data_validation:
  root_dir: artifacts/sentiment/data_validation/
  status_file: artifacts/sentiment/data_validation/status.txt


sentiment_data_transformation:
  root_dir: artifacts/sentiment/data_transformation/
  dataset_path: artifacts/sentiment/data_ingestion/processed 
  tokenizer_name: bert-base-cased   


# Use case specific - Sentiment
sentiment_model_trainer_and_evaluation:
  root_dir: artifacts/sentiment/model_trainer/model
  pre_trained_model_name: bert-base-cased 
  model_ckpt: artifacts/sentiment/model_trainer/model/best_model_state.bin


#<-------------- Summarization ----------------------->
summarizer_data_ingestion:
  root_dir: artifacts/summarizer/data_ingestion  
  unzip_dir: artifacts/summarizer/data_ingestion
  local_data_file: artifacts/summarizer/data_ingestion/data.zip
  # use-case specific parameters
  source_URL: "sunnysai12345/news-summary"  
  outsource_file: news-summary.zip


summarizer_data_validation:
  root_dir: artifacts/summarizer/data_validation/
  status_file: artifacts/summarizer/data_validation/status.txt


summarizer_data_transformation:
  root_dir: artifacts/summarizer/data_transformation
  dataset_path: artifacts/summarizer/data_ingestion/processed 
  tokenizer_name: google/summarizer/pegasus-cnn_dailymail  


summarizer_model_trainer_and_evaluation:
  root_dir: artifacts/model_trainer/summarizer/model
  pre_trained_model_name: bert-base-cased 
  model_ckpt: artifacts/model_trainer/summarizer/model/sentiment_best_model_state.bin